export const NODE_WIDTH = 240;
export const NODE_CENTER = NODE_WIDTH / 2;

export const CIRCUIT_SIZE = 10000;
export const CIRCUIT_CENTER = CIRCUIT_SIZE / 2;
export const CIRCUIT_POSITION_OFFSET_X = CIRCUIT_CENTER - NODE_CENTER;
export const CIRCUIT_POSITION_OFFSET_Y = CIRCUIT_CENTER;
